pipeline {
    docker {
        image 'node:16-alpine'
        args '-u node'
    }
    stages {
        stage('Install Dependencies') {
            steps {
                dir('single-agent') {
                    sh 'npm install'
                }
            }
        }
        stage('Test') {
            steps {
                // This command will run the 'test' script from package.json
                 dir('single-agent') {
                    sh 'npm test'
                }
            }
        }
    }
}