pipeline {
    agent {
        docker {
            image 'node:16-alpine'
            args "-u ${sh(returnStdout: true, script: 'id -u').trim()}:${sh(returnStdout: true, script: 'id -g').trim()}"
        }
    }
    stages {
        stage('Install Dependencies') {
            steps {
                dir('single-agent') {
                    sh 'npm install'
                }
            }
        }
        stage('Test') {
            steps {
                // This command will run the 'test' script from package.json
                 dir('single-agent') {
                    sh 'npm test'
                }
            }
        }
    }
}